export default function AnimatedUnderline() {
  return (
    <span
      className="
        pointer-events-none
        absolute
        bottom-0
        left-0
        h-px
        w-full
        overflow-hidden
      "
    >
      <span
        className="
          absolute
          inset-0
          origin-right
          scale-x-100
          bg-current
          transition-transform
          duration-500
          ease-[cubic-bezier(0.76,0,0.24,1)]
          group-hover:scale-x-0
        "
      />

      <span
        className="
          absolute
          inset-0
          origin-left
          scale-x-0
          bg-current
          transition-transform
          duration-500
          delay-0
          ease-[cubic-bezier(0.76,0,0.24,1)]
          group-hover:scale-x-100
          group-hover:delay-[180ms]
        "
      />
    </span>
  );
}
