import type { Metadata } from "next";
import {
  Cormorant,
  Cormorant_Upright,
  EB_Garamond,
  Forum,
  Geist,
  Geist_Mono,
  Inter,
  Libre_Baskerville,
  Lora,
  Lusitana,
  Marcellus,
  Marcellus_SC,
  Playfair_Display_SC,
  Spectral,
  Spectral_SC,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const lusitana = Lusitana({
  subsets: ["latin"],
  variable: "--font-lusitana",
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${lusitana.variable}`}>
        <div className="w-full h-full overflow-x-clip">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
